version: '3.8'

services:
  auth-server:
    build: ./auth-server
    ports:
      - "3000:3000"
    environment:
      - DB_URI=mongodb://mongo:27017
    depends_on:
      - mongo

  expense-server:
    build: ./expense-server
    ports:
      - "3001:3001"
    environment:
      - DB_URI=mongodb://mongo:27017
    depends_on:
      - mongo

  expense-group-server:
    build: ./expense-group-server
    ports:
      - "3002:3002"
    environment:
      - DB_URI=mongodb://mongo:27017
    depends_on:
      - mongo

  vuejs:
    build: ./fe
    ports:
      - "5173:5173"
    depends_on:
      - auth-server
      - expense-server
      - expense-group-server

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
